server:
  port:

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url:
    username:
    password:

  kafka:
    bootstrap-servers: #localhost:9092

  rabbitmq:
    host: #localhost
    port: 5672


